services:
    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/laravel
        depends_on:
            -   app
        user: 0:0
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/laravel
        depends_on:
            -   mysql
        user: 0:0
    mysql:
        image: mysql:8.4
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=laravel_db
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - mysql:/var/lib/mysql
        user: 0:0
volumes:
    mysql:
